#!/system/bin/sh
#
# Print startup info
#
L="log -p i -t turbo"

$L "_____  _     ___   ___   ___  ";
$L " | |  | | | | |_) | |_) / / \ ";
$L " |_|  \_\_/ |_| \ |_|_) \_\_/ ";
$L "Welcome to Android `getprop ro.build.version.release` / Turbo ROM-`getprop ro.turbo.version`";
