# Version of the ROM
CANDY_CODENAME := O
CANDY_REVISION := V1.0

ifndef CANDY_BUILDTYPE
  CANDY_BUILDTYPE := UNOFFICIAL
endif

TARGET_PRODUCT_SHORT := $(TARGET_PRODUCT)
TARGET_PRODUCT_SHORT := $(subst candy_,,$(TARGET_PRODUCT_SHORT))

CANDY_VERSION := $(CANDY_REVISION)-$(CANDY_CODENAME)-$(CANDY_BUILDTYPE)-$(TARGET_PRODUCT_SHORT)-$(shell date -u +%Y%m%d-%H%M)

PRODUCT_BUILD_PROP_OVERRIDES += BUILD_DISPLAY_ID="$(BUILD_ID)-$(shell whoami)@$(shell hostname)"

# Apply it to build.prop
PRODUCT_PROPERTY_OVERRIDES += \
    ro.modversion=Candy-$(CANDY_VERSION) \
    ro.candy.version=$(CANDY_VERSION) \
