#!/bin/sh
#
# Super-mega crusher of doom
# Shrinks apks by running pngquant or pngcrush or optipng or pngout on png images
#
# Point APKCERTS at the full path to a generated apkcerts.txt file, such as:
# /home/shade/dev/sources/android-cm-eclair/out/target/product/dream_sapphire/obj/PACKAGING/target_files_intermediates/cyanogen_dream_sapphire-target_files-eng.shade/META/apkcerts.txt
#
# cyanogen - shade@chemlab.org
# ChrisSoyars - me@ctso.me
# Nougat fixes: Joe Maples - frap129@gmail.com

set -e
BASE=`pwd`

. $ANDROID_BUILD_TOP/vendor/candy/tools/colors

if [ "$(which pngquant 2>/dev/null)" != "" ]; then
    if [ "$(which optipng 2>/dev/null)" != "" ]; then
        optimize_png () {
            pngquant --speed 1 --force --ext .png $1 1> /dev/null 2> /dev/null;
            optipng -o7 $1 1> /dev/null 2> /dev/null;
        }
    else
        optimize_png () {
            pngquant --speed 1 --force --ext .png $1 1> /dev/null 2> /dev/null
        }
    fi
else
    if [ "$(which optipng 2>/dev/null)" != "" ]; then
        optimize_png () {
            optipng -o7 $1 1> /dev/null 2> /dev/null;
        }
    else
        echo $CL_RED"Please install pngquant or optipng (or both, for improved crushing)"$CL_RST
        exit 1;
    fi
fi

if [ -e "$1" ]; then
    NAME=`basename $1`;
    cd $NAME
    for x in `find . -name "*.png" | grep -v "\.9.png$" | tr "\n" " "`; do
        optimize_png $x
    done
fi
